# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250512-193237-flashed-banner

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es
pipeline:
- name: SpacyNLP
  model: es_core_news_sm
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
  random_seed: 42
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  random_seed: 42
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  random_seed: 42
- name: RulePolicy
